export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const GET_NUMBERS_BASKET = "GET_NUMBERS_BASKET";
export const POST_PRODUCT_TO_CART = "POST_PRODUCT_TO_CART";
export const GET_PRODUCTS_OF_CART = "GET_PRODUCTS_OF_CART";

